/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import ticket.booking.services.UserBookingService;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        System.out.println("RUnning the train booking system");
        Scanner sc = new Scanner(System.in);
        int option = 0;

        UserBookingService userBookingService;
        
    }
}
