/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import ticket.booking.entities.Train;
import ticket.booking.entities.User;
import ticket.booking.services.UserBookingService;
import ticket.booking.util.UserServiceUtil;

import java.util.*;

public class App {

    public static void main(String[] args) {
        System.out.println("Running the train booking system");
        Scanner sc = new Scanner(System.in);
        int option = 0;

        UserBookingService userBookingService = null;
        try {
            userBookingService = new UserBookingService();
        } catch (Exception e) {
            System.out.println("Error in UserBookingService" + e.getMessage());
            e.printStackTrace();
        }
        if (userBookingService == null) {
            System.out.println("Booking service not available. Exiting...");
            return;
        }

        while (option != 7) {
            System.out.println("Please enter your choice");
            System.out.println("1. Sign UP");
            System.out.println("2. Login");
            System.out.println("3. Fetch Bookings");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a seat");
            System.out.println("6. Cancel Booking");
            System.out.println("7. Exit");

            option = sc.nextInt();
            switch (option) {
                case 1:
                    System.out.println("Enter the UserName to signup");
                    String userName = sc.next();
                    System.out.println("Enter the Password to signup");
                    String password = sc.next();
                    User userToSignUp = new User(userName, password, UserServiceUtil.hashPassword(password), new ArrayList<>(), UUID.randomUUID().toString());
                    userBookingService.signUp(userToSignUp);
                    break;

                case 2:
                    System.out.println("Enter the UserName to Login");
                    String nameTOLogin = sc.next();
                    System.out.println("Enter the Password to Login");
                    String passwordTOLogin = sc.next();
                    User userToLogin = new User(nameTOLogin, passwordTOLogin, UserServiceUtil.hashPassword(passwordTOLogin), new ArrayList<>(), UUID.randomUUID().toString());
                    try {
                        userBookingService = new UserBookingService(userToLogin);
                        System.out.println(userBookingService.loginUser());
                    } catch (Exception ex) {
                        System.out.println("error while trying to login: " + ex);

                        return;
                    }
                    break;

                case 3:
                    System.out.println("Fetch Your Bookings");
                    userBookingService.fetchBooking();
                    break;

                case 4:
                    System.out.println("Type Your Source Station");
                    String sourceStation = sc.next();
                    System.out.println("Type Your Destination Station");
                    String destinationStation = sc.next();
                    List<Train> trainList = null;
                    trainList = userBookingService.getTrains(sourceStation, destinationStation);
                    int index = 1;
                    for (Train train : trainList) {
                        System.out.println(index + "Train ID: " + train.getTrainID());
                        for (Map.Entry<String, String> entry : train.getStationTime().entrySet()) {
                            System.out.println(index + "Station : " + entry.getKey() + " Time: " + entry.getValue());
                            index++;
                        }
                    }
                case 5:
                    System.out.println("Enter Your Seat Number");

            }


        }
    }
}
