/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import ticket.booking.entities.Train;
import ticket.booking.entities.User;
import ticket.booking.services.UserBookingService;
import ticket.booking.util.UserServiceUtil;

import java.util.*;

public class App {

    public static void main(String[] args) {
        System.out.println("Running the train booking system");
        Scanner sc = new Scanner(System.in);
        int option = 0;

        UserBookingService userBookingService = null;
        try {
            userBookingService = new UserBookingService();
        } catch (Exception e) {
            System.out.println("Error in UserBookingService" + e.getMessage());
            e.printStackTrace();
        }
        if (userBookingService == null) {
            System.out.println("Booking service not available. Exiting...");
            return;
        }
        Train trainSelectedForBooking = new Train();
        String source = null;
        String destination = null;
        while (option != 7) {
            System.out.println("Please enter your choice");
            System.out.println("1. Sign UP");
            System.out.println("2. Login");
            System.out.println("3. Fetch Bookings");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a seat");
            System.out.println("6. Cancel Booking");
            System.out.println("7. Exit");

            option = sc.nextInt();
            switch (option) {
                case 1:
                    System.out.println("Enter the UserName to signup");
                    String userName = sc.next();
                    System.out.println("Enter the Password to signup");
                    String password = sc.next();
                    User userToSignUp = new User(userName, password, UserServiceUtil.hashPassword(password), new ArrayList<>(), UUID.randomUUID().toString());
                    userBookingService.signUp(userToSignUp);
                    break;

                case 2:
                    System.out.println("Enter the UserName to Login");
                    String nameTOLogin = sc.next();
                    System.out.println("Enter the Password to Login");
                    String passwordTOLogin = sc.next();
                    User userToLogin = new User(nameTOLogin, passwordTOLogin, null, new ArrayList<>(), null);
                    try {
                        userBookingService = new UserBookingService(userToLogin);
                        System.out.println(userBookingService.loginUser());
                    } catch (Exception ex) {
                        System.out.println("error while trying to login: " + ex);
                        return;
                    }
                    break;

                case 3:
                    System.out.println("Fetch Your Bookings");
                    userBookingService.fetchBooking();
                    break;

                case 4:
                    System.out.println("Type Your Source Station");
                    source = sc.next();
                    System.out.println("Type Your Destination Station");
                    destination = sc.next();
                    List<Train> trainList = null;
                    trainList = userBookingService.getTrains(source, destination);
                    int index = 1;
                    for (Train train : trainList) {
                        System.out.println(index + "Train ID: " + train.getTrainID());
                        for (Map.Entry<String, String> entry : train.getStationTime().entrySet()) {
                            System.out.println(index + "Station : " + entry.getKey() + " Time: " + entry.getValue());
                        }
                        index++;
                    }
                    System.out.println("Select a train by typing 1,2,3..");
                    trainSelectedForBooking = trainList.get(sc.nextInt() - 1);
                    break;
                case 5:
                    if (trainSelectedForBooking == null) {
                        System.out.println("Please select a train before trying to book a seat");
                        break;
                    }
                    System.out.println("Select a seat out of these");
                    List<List<Integer>> seats = userBookingService.fetchSeats(trainSelectedForBooking);
                    for (List<Integer> seat : seats) {
                        for (Integer i : seat) {
                            System.out.print(i + " ");
                        }
                        System.out.println();
                    }
                    System.out.println("Select the seat by typing the row and column");
                    System.out.println("Enter the row");
                    int row = sc.nextInt();
                    System.out.println("Enter the column");
                    int col = sc.nextInt();
                    System.out.println("Booking your seat....");
                    Boolean booked = userBookingService.bookSeat(trainSelectedForBooking, row, col, source, destination);
                    if (booked == Boolean.TRUE) {
                        System.out.println("Seat has been booked");
                    } else {
                        System.out.println("Seat has been not booked");
                    }
                    break;
                case 6:
                    System.out.println("Cancel Booking");
                default:
                    break;
            }


        }
    }
}
